### ISSUE TITLE
New getPath Method for phpBB Connector

### ISSUE THREAD

**Issue by mvscheidt** [ctsmedia/contao-phpbb-bridge-bundle#10]
As discussed - add a `getPath` Method to the Connector which returns the forums path

**Comment by mvscheidt** [comment]
@DanielSchwiperich

**Comment by DanielSchwiperich** [comment]
Temporarily you can use `System::getContainer()->get('phpbb_bridge.connector')->getConfig('contao.forum_pageAlias')` Just for info / documentation
