### ISSUE TITLE
Page type phpbb_forum does not honor usage of app_dev.php

### ISSUE THREAD

**Issue by mvscheidt** [ctsmedia/contao-phpbb-bridge-bundle#14]
If you use the app_dev.php entry point the forum page doesn't generate the correct link.

Though I am not entirely sure if that would work regarding phpBB.

If it doesn't this should be documented under a section "Known Issues" / "Known Limitations" or something along those lines.

---

Expected Result (app_dev.php being used):

http://domain.local/app_dev.php/forum/index.php

Actual Result (app_dev.php gets lost): 

http://domain.local/forum/index.php

**Comment by DanielSchwiperich** [comment]
Yes this does not work since the linking to the forum works with a true symlink. Contao is not a proxy anymore. 
There would also be no benefit because phpbb does not such an dev mode like contao has. 

I leave this open, until I've updated the README
