### ISSUE TITLE
Join 'phpbb_profile_fields_data' in the getUser() Connector Method 

### ISSUE THREAD

**Issue by mvscheidt** [ctsmedia/contao-phpbb-bridge-bundle#15]
As the title implies, join the data of the table `phpbb_profile_fields_data` when calling the `getUser()` Method of the PhpBB Connector.

Alternatively add a new Method like `getUserDetails($userId)` which returns data from the phpbb_profile_fields_data table

**Comment by DanielSchwiperich** [comment]
`getUserProfile($userID)` method added
