### ISSUE TITLE
Symlink in tl_page::generatePhpbbLink() wrong set

### ISSUE THREAD

**Issue by DanielSchwiperich** [ctsmedia/contao-phpbb-bridge-bundle#2]
The set symlink is a fixed one and not compatible to most systems

https://github.com/ctsmedia/contao-phpbb-bridge-bundle/blob/master/src/Resources/contao/dca/tl_page.php#L64

/cc @ctsmedia/cts-developer

**Comment by mvscheidt** [comment]
Sehr geehrte Damen und Herren,

vielen Dank für Ihre e-Mail. Ich bin vom 21.12. bis einschließlich 01.01.2016 nicht erreichbar und erst am 04.01.2016 wieder im Hause.

In dieser Zeit werden meine Mails nicht gelesen. Bitte wenden Sie sich in dringenden Fällen an meine Kollegen.

-per Mail: d.schwiperich@cts-media.eu / info@cts-media.eu

-telefonisch: 0221/168814-0

Mit freundlichen Grüßen,

Mike vom Scheidt

----

Thank you for your message. I am currently out of the office and will be back on Monday, January 04, 2016. If you need immediate assistance please contact the office, +49-221-1688140, d.schwiperich@cts-media.eu or info@cts-media.eu

Kind regards Mike vom Scheidt
