### ISSUE TITLE
Bridge Logo 

### ISSUE THREAD

**Issue by DanielSchwiperich** [ctsmedia/contao-phpbb-bridge-bundle#20]
We need a logo for the bridge.

Talk to me @t-muir :wink:

**Comment by t-muir** [comment]
three revised versions of the logo drafts:

![c2bb-logo-3d](https://cloud.githubusercontent.com/assets/14332656/13598832/49308f3c-e520-11e5-9572-c0ee834dfeb9.png)
![c2bb-logo-simple](https://cloud.githubusercontent.com/assets/14332656/13598830/493013ea-e520-11e5-88e5-e3cc26fb659e.png)
![c2bb-teeth-logo](https://cloud.githubusercontent.com/assets/14332656/13598831/49304202-e520-11e5-801f-6c48424d5eb3.png)

**Comment by DanielSchwiperich** [comment]
@t-muir I need the icon sized version of Nr 1 (since it's the one we decided for). So around 18px x 18px would be fine

**Comment by t-muir** [comment]
three sizes. The 36px should be good - it should scale well to 18px and still display nicely on retina displays.

![logo_c2bb-18](https://cloud.githubusercontent.com/assets/14332656/14010599/eee43e2e-f196-11e5-963f-ec753c8e3160.png)
![logo_c2bb-36](https://cloud.githubusercontent.com/assets/14332656/14010600/eee4b534-f196-11e5-8cc4-a2c9146698c3.png)
![logo_c2bb-100](https://cloud.githubusercontent.com/assets/14332656/14010601/eee80c2a-f196-11e5-8339-2f74871fb014.png)

**Comment by DanielSchwiperich** [comment]
thanks Tom, but I need the 18px also because in the contao backend the icon get not scaled and it would break the layout then. 
I also need a greyed version of the 18px as unpublished state indicator. Sorry for the inconveniences

**Comment by t-muir** [comment]
No worries!

![logo_c2bb-18](https://cloud.githubusercontent.com/assets/14332656/14011244/5ea22a2c-f19d-11e5-820b-db602a87d926.png)
![logo_c2bb-18-grey](https://cloud.githubusercontent.com/assets/14332656/14011245/5eb756fe-f19d-11e5-906f-b1a62c19b1d5.png)
