### ISSUE TITLE
Deactivate check of Session-IP for Bridge Requests

### ISSUE THREAD

**Issue by mvscheidt** [ctsmedia/contao-phpbb-bridge-bundle#23]
As discussed with Daniel, deactivate the Check of the Session IP in phpBB for Bridge Requests.

Background: Caused issues with my Docker Container IP Addresses

172.17.0.8 (docker container itself)
172.17.42.1 (output of ifconfig for docker0)

/cc @ctsmedia/cts-developer

**Comment by DanielSchwiperich** [comment]
Now pushed as mandatory value (=> 0)
