### ISSUE TITLE
Cookie Expiration wrong on Contao login

### ISSUE THREAD

**Issue by DanielSchwiperich** [ctsmedia/contao-phpbb-bridge-bundle#27]
If logged via Contao the expiration of the phpbb autologin cookie gets set to _session_ instead of the correct value.

We need also to recheck the other cookie expirations.

/cc @ctsmedia/cts-developer

**Comment by mvscheidt** [comment]
Sehr geehrte Damen und Herren,

vielen Dank für Ihre e-Mail. Ich bin vom 21.03. bis einschließlich 01.04. nicht erreichbar und erst am 04.04. wieder im Hause.

In dieser Zeit werden meine Mails nicht gelesen. Bitte wenden Sie sich in dringenden Fällen an meine Kollegen.

-per Mail: info@cts-media.eu / d.schwiperich@cts-media.eu / t.siefert@cts-media.eu

-telefonisch: +49 (0)221 – 16 88 14 00


Mit freundlichen Grüßen,

Mike vom Scheidt

-----------------

Dear Sir or Madam,

thank you for your message. I am currently out of the office and will be back on Monday, April 4, 2016.

If you need immediate assistance please contact the office:

-E-Mail: info@cts-media.eu / d.schwiperich@cts-media.eu / t.siefert@cts-media.eu

-Telephone: +49 (0)221 – 16 88 14 00


Kind regards,

Mike vom Scheidt
