### ISSUE TITLE
Logout Error / Not Working

### ISSUE THREAD

**Issue by aethys256** [ctsmedia/contao-phpbb-bridge-bundle#31]
Hello,

I did installed the bundle for one of our customer, I followed every steps for the installation and I can get the forum integration & sync in Contao working.
Unfortunately, I have a php error on the logout.

I double checked the installation steps and everything looks fine.

Here is the screenshot of the error:
![contao_phpbb_bridge_error](https://user-images.githubusercontent.com/10969743/28868827-ee23b378-777a-11e7-8c07-19ab98629df6.png)

As shown in the screenshot the Contao version is 4.4.2 and the Symfony version is 3.3.6.
The phpBB version is 3.1.11.

I tried multiple things (based on what I've seen in Contao Core Bundle) but it was returning null, so for now I removed the second part of the if to make the logout working, although I think it would be a good idea to let you know.

**Comment by DanielSchwiperich** [comment]
Thanks for the report. I've not tested the bridge with contao 4.4 LTS and Symfony 3.3 yet. 
At least Symfony had some BC breaking changes. 
Will hopefully do so soon. 

Could you try in the meantime to replace `'request'` with  `'request_stack'` in the mentioned file. Maybe that already solves the problem for you

**Comment by aethys256** [comment]
Already tried, was returning `null` (then a php error).
Didn't spend much time trying to debug it yet.

**Comment by DanielSchwiperich** [comment]
`System::getContainer()->get('request_stack')->getCurrentRequest()` should fix it. 
could you pls test it?

will be in a later release then
