### ISSUE TITLE
Contao 4.4.3

### ISSUE THREAD

**Issue by MicioMax** [ctsmedia/contao-phpbb-bridge-bundle#32]
Hi,

I've seen that instructions are outdated for Contao 4.4.
I tried to do it manually, but differences are too many.
Is it possible to install the bridge on it or we shall wait for an update ?

**Comment by DanielSchwiperich** [comment]
Hi, 
it should work. 
there may be one bug though: https://github.com/ctsmedia/contao-phpbb-bridge-bundle/issues/31

I've not tested it yet with contao 4.4 and also not updated it to make it compatible to the managed edition. 
The manual installation process should still work so. 

I will test and make it compatible to the managed edition asap, but no eta yet since my time is very limited at the moment

**Comment by FlowinBeatz** [comment]
Hey Daniel,

I'm also waiting on an update for Contao 4.4 and also for compatibility for the managed edition.
Would some money help to speed things up?

**Comment by DanielSchwiperich** [comment]
Hi 030media, 
sure it would help so I can prioritize it or let an employee work on it. 

But maybe I can  already start thursday working on it if things go well.

**Comment by FlowinBeatz** [comment]
As we are kind of "gemeinnützig" I would prefer to wait if you can start it this week.

However, you time and effort is highly appreciated!

**Comment by FlowinBeatz** [comment]
Do you have any news? Thanks in advance!

**Comment by DanielSchwiperich** [comment]
I just started, but will first do some docker and general dev updates to be more in line with our current company status and features. 
After that I'll get directly to the contao 4.4 compatible update

**Comment by DanielSchwiperich** [comment]
just wanna let you know that I'm on it. Sorry for the slow progress but got heavy work load. 
Expect it by next week

**Comment by FlowinBeatz** [comment]
Thank you so much!

**Comment by DanielSchwiperich** [comment]
Just a quick heads up. Most of it is already Contao 4.4 / ME compatible. Seems to also work fine with phpbb 3.2 (which supports php 7).

Some small issues left. Should be finished in the next few days

**Comment by DanielSchwiperich** [comment]
In master branch the update is online. Tomorrow I will release a new version which is the same but has phpbb extension side dependencies pre installed. So there should be no need to do anything via cli

**Comment by FlowinBeatz** [comment]
Yeah! Thank you so much. Will I find it on packagist / composer? Or do I still have to download the package here?

**Comment by DanielSchwiperich** [comment]
it will be on packagist. But also directly installable with the contao manager

**Comment by DanielSchwiperich** [comment]
Update is released [1.1](https://github.com/ctsmedia/contao-phpbb-bridge-bundle/releases/tag/1.1.0)

It's now compatible to the managed edition and can also be installed via the contao manger. 
[install docs for ME](https://github.com/ctsmedia/contao-phpbb-bridge-bundle/blob/master/doc/installation.md#managed-edition-with-contao-manager)

Let me know if you experience any problems. Also interested in general feedback. 

It's also on packagist https://packagist.org/packages/ctsmedia/contao-phpbb-bridge-bundle

for now I close here
