### ISSUE TITLE
phpBB does not recognize Contao

### ISSUE THREAD

**Issue by FlowinBeatz** [ctsmedia/contao-phpbb-bridge-bundle#35]
I am stuck in the [installation process](https://github.com/ctsmedia/contao-phpbb-bridge-bundle/blob/master/doc/installation.md) on step 6. No matter how often I purge the cache, I don't see any Contao related things in the "Manage Extensions" area of phpBB.

Also in the Authentication area of the phpBB backend there is no "Contao" entry. 

Since I logged out of phpBB and tried to re-login I am not able to login, even if the login credentials are 100% correct.

What should I do know?

**Comment by FlowinBeatz** [comment]
The "restore password" function doesn't work as well: Das übermittelte Formular war ungültig. Versuche erneut, das Formular abzusenden.

**Comment by DanielSchwiperich** [comment]
Welche phpbb Version nutzt du? 3.1 oder 3.2

Ich hatte in meinen Tests einmal den Fall (konnte ich aber nicht reproduzieren), das die extension nicht korrekt ins Forum gelinked wurde. 
Einfachste Lösung war im Contao Backend die Forums Seite zu löschen und neu anzulegen. 

Danach dann mal schauen im phpbbdir/ext ob dort der ctsmedia symlink exisitiert. Vermutlich wird der aktuell nicht existieren. 

Ich werde dann nächste mal Woche schauen, was das verursachen kann das der Symlink nicht korrekt angelegt wird. Sorry für die Umstände

**Comment by FlowinBeatz** [comment]
Nutze phpBB 3.2.1

Seite gelöscht und neu angelegt. Sah auch erstmal erfolgreich aus: https://www.evernote.com/l/AYEJPjBD7y1Go5fe1DZGHkIiLXn8pdYrdbQ

Ich kann mich aber nicht mehr ins phpBB einloggen :-(

**Comment by FlowinBeatz** [comment]
OK, habe die phpBB Cookies gelöscht, dann ging der Login.
Ich habe dann auch die Extension gesehen und aktiviert, außerdem die Authentication auf "Contao" gesetzt.

--> Seite löschen und neu anlegen scheint schon mal zu helfen!

Leider funktioniert der Sync dennoch nicht. Kann man das irgendwie Debuggen, was da im Hintergrund vielleicht hakt?

**Comment by DanielSchwiperich** [comment]
Guter Hinweis mit dem Login. Hatte das auch in dem Zusammenhang (dann aber einfach Forum neu installiert da ich dachte ich haätte mich vertippt. )
Da scheint ein kleiner Bug zu sein. Werde ich mir mal anschauen. 

Wegen dem Sync, der geht aktuell nur in eine Richtung. Forum User werden ins Contao importiert. 
Du musst in der Seiten Konfig angeben in welche Member Gruppe die dann landen sollen. 

Der Contao Part schreibt in den normalen Contao Log der über das Backend einsehbar ist. Der phpbb part hat 2 Log files. 
Einen allgemeinen und einen für errors. 
Die Beiden liegen phpbbdir/ext/ctsmedia/contaophpbbbridge/

Schau mal bitte was die bridge im contao und phpbb bridge log sagen.

**Comment by FlowinBeatz** [comment]
Das mit dem Sync hatte ich genau andersrum verstanden... Das ist für uns aber blöd gelaufen. Da wir viele Custom Fields haben und schon ne Menge Sachen in einem internen Mitgliederbereich machen, war es uns nur so möglich, auch ein Forum zu haben.

Was müsste man tun, damit es auch andersrum funktioniert?

Bzgl. der Logs: ich kann dem Symlink leider nicht folgen.. Wo führt der hin?

**Comment by DanielSchwiperich** [comment]
In dem Verzeichniss liegen die bridge logs von phpbb logs: `vendor/ctsmedia/contao-phpbb-bridge-bundle/src/Resources/phpBB/ctsmedia/contaophpbbbridge/`

Kannst du dich denn anmelden mit dem (Admin)user vom phpbb am Contao Frontend? Der sollte dann importiert werden. 

Mir war klar, dass der Request irgendwann kommen wird. 😃 

Es sollte nicht so kompliziert / aufwendig sein, dass auch in die andere Richtung hinzubekommen. 
Ich weiss aber nicht ob ich das diese Woche schaffen werde

**Comment by FlowinBeatz** [comment]
Log gefunden!
Steht auch einiges drin, sagt mir aber alles nicht so viel.

Beim Login eines neuen, über phpBB erstellten, Benutzers in phpBB selbst kommt folgende Fehlermeldung:
> Konnte nicht bei Contao einloggen. Bitte erneut versuchen oder Support kontaktieren.

Der Admin Account von phpbb matcht leider mit meinem Frontend User aus Contao, daher war das nicht so aussagekräftig.

**Comment by DanielSchwiperich** [comment]
Ja das wird dann das Problem sein, wenn die Passwörter unterschiedlich sind. Er kann dich im Forum einloggen aber nicht am Contao. 

Haben wir dann jetzt aktuell noch ein Problem / Bug?

- Die Installation ist gefixed. Das werd ich mir aber noch anschauen, dass es gar nicht mehr auftritt
- Sync richtung contao geht nicht, weil user schon existiert
- Umgekehrter Sync ist nicht implementiert aktuell

Dann würde ich ein Ticket aufmachen für den umgekehrten Sync und nochmal den Installationsprozess prüfen warum es zu dem kaputten / nicht existierenden Symlink kommt

**Comment by FlowinBeatz** [comment]
Es muss dennoch ein Bug vorliegen.
Habe einen neuen Account auf phpBB angelegt, dieser wurde nicht nach Contao übertragen und ich kann mich auch nicht einloggen.

**Comment by DanielSchwiperich** [comment]
ok. Kannst du mal die logs clearen und dann dich versuchen mit dem User anzumelden und die Logs hier dann attachen bzw. den contao log posten. 

In meinem dev setup geht das ohne Probleme, deswegen kann ich das nicht direkt nachvollziehen.

**Comment by FlowinBeatz** [comment]
Das passiert beim Login. Oder meinst Du bei der Registrierung?


[2017-10-30 17:41:42] bridge_connector.ERROR: __LAYOUT__--------------------------- [] []
[2017-10-30 17:41:42] bridge_connector.ERROR: Json Response expected. Got:  {"status":403} []
[2017-10-30 17:41:42] bridge_connector.ERROR: Set-Cookies:  [null] []
[2017-10-30 17:41:42] bridge_connector.ERROR: REQ--------------------------- [] []
[2017-10-30 17:41:42] bridge_connector.ERROR: Inc ath ["/forum/ucp.php?mode=login"] []
[2017-10-30 17:41:42] bridge_connector.ERROR: Path ["/phpbb_bridge/layout"] []
[2017-10-30 17:41:42] bridge_connector.ERROR: Cookies ["BE_PAGE_OFFSET=0; PHPSESSID=vtf9v72s2o2m2lfu1rnhrdu93u; phpbb3_frphx_u=1; phpbb3_frphx_k=; phpbb3_frphx_sid=accf2c0392fcc02868fdd168f94409c8"] []
[2017-10-30 17:41:42] bridge_connector.ERROR: Append [""] []
[2017-10-30 17:41:51] bridge_connector.ERROR: __LAYOUT__--------------------------- [] []
[2017-10-30 17:41:51] bridge_connector.ERROR: Json Response expected. Got:  {"status":403} []
[2017-10-30 17:41:51] bridge_connector.ERROR: Set-Cookies:  [null] []
[2017-10-30 17:41:51] bridge_connector.ERROR: REQ--------------------------- [] []
[2017-10-30 17:41:51] bridge_connector.ERROR: Inc ath ["/forum/ucp.php?mode=login"] []
[2017-10-30 17:41:51] bridge_connector.ERROR: Path ["/phpbb_bridge/layout"] []
[2017-10-30 17:41:51] bridge_connector.ERROR: Cookies ["BE_PAGE_OFFSET=0; PHPSESSID=vtf9v72s2o2m2lfu1rnhrdu93u; phpbb3_frphx_u=1; phpbb3_frphx_k=; phpbb3_frphx_sid=accf2c0392fcc02868fdd168f94409c8"] []
[2017-10-30 17:41:51] bridge_connector.ERROR: Append [""] []

**Comment by DanielSchwiperich** [comment]
ah interessant. schon beim anfragen des layouts kommt ein forbidden. 
Schau mal in den Contao Log im Backend. Da müsste der Grund dafür drin stehen.

**Comment by FlowinBeatz** [comment]
> [30.10.2017 20:17] IPs did not match. clientIP: 80.187.80.244\| EnvClientIp 80.187.80.244\| EnvServerIp 185.194.141.154

**Comment by DanielSchwiperich** [comment]
ok damit ist die Bridge gar nicht in _Betrieb_. Nutzt du das Docker Setup zum testen oder hast php fpm im Einsatz auf einem anderen server als den Webserver?


guck mal hier: [troubleshooting docs](https://github.com/ctsmedia/contao-phpbb-bridge-bundle/blob/master/doc/faq-troubleshooting.md#q-bridge-is-not-functioning-correct-log-states-ips-did-not-match-clientip-xxxxxxxxxxxx-envclientip-xxxxxxxxxxxx-envserverip-yyyyyyyyyyyy)
wenn du den konfig param setzt sollte es gehen. ggf. cache leeren.

**Comment by FlowinBeatz** [comment]
Gemeint ist /config/production/container/parameters.yml?

Oder die dort importierte default/container/parameters.yml?

**Comment by FlowinBeatz** [comment]
Habe mich jetzt übrigens klassisch ausgesperrt, weil der Login mit meinem Admin account ja auch nicht mehr klappt: Login bei Contao nicht möglich ^^

**Comment by DanielSchwiperich** [comment]
auf das backend hat der login keinen Einfluss. Oder meinst du das frontend?

die app/config/parameters.yml also die zentrale konfig.

**Comment by FlowinBeatz** [comment]
Ah, ich dachte an die phpBB parameters.yml. Anschließend über Contao den phpBB Cache geleert.

Hab es eingetragen, was zu einem 500er Fehler führt :-(

> auf das backend hat der login keinen Einfluss. Oder meinst du das frontend?

Ich bezog das auf den phpBB Login. Dort funktioniert jetzt mein Admin Account auch nicht mehr, weil der Login ja auf Contao zugreifen möchte.

**Comment by DanielSchwiperich** [comment]
ich würde mal tippen beim copy and paste würde ein ungültiges Zeichen mit in die yml kopiert. 
Ansonsten mal in den php / apache error log gucken und bescheid geben was für ein error gemeldet wird

**Comment by FlowinBeatz** [comment]
> [Mon Oct 30 21:53:40.085363 2017] [proxy_fcgi:error] [pid 27243] [client 87.184.168.85:34190] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Symfony\\Component\\Yaml\\Exception\\ParseException: A YAML file cannot contain tabs as indentation at line 22 (near "\tphpbb_bridge.allow_external_ip_access: true"). in /var/www/vhosts/xxx/web/forum/vendor/symfony/yaml/Parser.php:125\nStack trace:\n#0 /var/www/vhosts/xxx/web/forum/vendor/symfony/yaml/Parser.php(80): Symfony\\Component\\Yaml\\Parser->doParse(Array, false, false, false)\n#1 /var/www/vhosts/xxx/web/forum/vendor/symfony/dependency-injection/Loader/YamlFileLoader.php(364): Symfony\\Component\\Yaml\\Parser->parse('parameters:\\n   ...')\n#2 /var/www/vhosts/xxx/web/forum/vendor/symfony/dependency-injection/Loader/YamlFileLoader.php(44): Symfony\\Component\\DependencyInjection\\Loader\\YamlFileLoader->loadFile('/var/www/vhosts...')\n#3 /var/www/vhosts/xxx/web/forum/vendor/symfony/config/Loader/FileLoader.php(1...\n'


Ich hab keine Ahnung, was das bedeutet ..

**Comment by DanielSchwiperich** [comment]
jo wie ich gedacht habe. mach aus dem tab spaces dann passt es.

**Comment by FlowinBeatz** [comment]
Das file ist nun schon frei von jeglichen Tabs und spaces, führt aber dennoch zum gleichen Fehler

**Comment by DanielSchwiperich** [comment]
spaces müssen ja drin sein. tabs sind nicht erlaubt in yml files. 
Das ist der relevante Part der Fehlermessage:
``` 
A YAML file cannot contain tabs as indentation at line 22 (near "\tphpbb_bridge.allow_external_ip_access: true"
```
Ein tab for dem Eintrag. Einfach via backspace entfernen und dann soviele spaces machen bis es mit dem darüber stehenden Eintrag passt. Der Fehler kann dann nicht mehr auftreten (oder er lautet anders)

**Comment by DanielSchwiperich** [comment]
Hast du es hinbekommen @030media ?

**Comment by FlowinBeatz** [comment]
Nein, habe ich leider nicht. Egal was ich tue, der Fehler bleibt. Sogar wenn ich die Zeile ganz rausnehme. Wird das irgendwo gecacht?

**Comment by DanielSchwiperich** [comment]
mach mal im projekt folder ein `rm -r var/cache/*`

**Comment by FlowinBeatz** [comment]
Kein Unterschied -_-

**Comment by DanielSchwiperich** [comment]
Stell die Datei mal hier ein

**Comment by FlowinBeatz** [comment]
[parameters.yml.zip](https://github.com/ctsmedia/contao-phpbb-bridge-bundle/files/1445783/parameters.yml.zip)

**Comment by DanielSchwiperich** [comment]
ja das ist kein tab mehr drin. 

Und die Fehlermeldung ist genau dieselbe wie weiter oben? Kannst du die Meldung die aktuell bekommst bitte nochmal posten

**Comment by FlowinBeatz** [comment]
Ja, exakt die gleiche. Auch wenn ich diese Zeile ganz rausnehme, passiert das.

`[Mon Nov 06 11:50:53.945740 2017] [proxy_fcgi:error] [pid 21290] [client 90.187.28.37:37634] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Symfony\\Component\\Yaml\\Exception\\ParseException: A YAML file cannot contain tabs as indentation at line 22 (near "\tphpbb_bridge.allow_external_ip_access: true"). in /var/www/vhosts/xxx/web/forum/vendor/symfony/yaml/Parser.php:125\nStack trace:\n#0 /var/www/vhosts/xxx/web/forum/vendor/symfony/yaml/Parser.php(80): Symfony\\Component\\Yaml\\Parser->doParse(Array, false, false, false)\n#1 /var/www/vhosts/xxx/web/forum/vendor/symfony/dependency-injection/Loader/YamlFileLoader.php(364): Symfony\\Component\\Yaml\\Parser->parse('parameters:\\n   ...')\n#2 /var/www/vhosts/xxx/web/forum/vendor/symfony/dependency-injection/Loader/YamlFileLoader.php(44): Symfony\\Component\\DependencyInjection\\Loader\\YamlFileLoader->loadFile('/var/www/vhosts...')\n#3 /var/www/vhosts/xxx/web/forum/vendor/symfony/config/Loader/FileLoader.php(1...\n'`

**Comment by DanielSchwiperich** [comment]
Das hört sich für mich an als ob dort noch eine parameters.yml liegt und den Eintrag hat. 
Hast du den Eintrag nur in einer Datei hinzugefügt?

Leider ist der Pfad hier gekürzt und man kann nicht genau erkennen welche Datei er lädt
`Symfony\\Component\\DependencyInjection\\Loader\\YamlFileLoader->loadFile('/var/www/vhosts...')\n#3 `

Du kannst auch mal posten was der command 
`grep -R "phpbb_bridge.allow_external_ip_access: true" ./` ergibt. (Im Projektfolder ausführen)

**Comment by DanielSchwiperich** [comment]
Fortschritte erzielt oder aufgegeben? 😃 
Das kann wie gesagt eigentlich nichts mit der Bridge zu tun haben. ggf. kann ich mir das sonst mal anschauen wenn du möchtest

**Comment by FlowinBeatz** [comment]
Gerade ein bisschen Arbeit und Krankheit dazwischen gekommen. Ich melde mich noch mal, sobald ich Ergebnisse habe.

Kannst Du irgendetwas zum "Aufbohren" der Bridge sagen, so dass es von Contao zu phpBB klappt?

**Comment by DanielSchwiperich** [comment]
wurde gelöst
