### ISSUE TITLE
BC Break in kriswallsmith/buzz 0.17.x

### ISSUE THREAD

**Issue by mvscheidt** [ctsmedia/contao-phpbb-bridge-bundle#43]
```
Attempted to call an undefined method named `setMaxRedirects` of class `Buzz\Client\Curl`
```

This can happen if you use composer to require our bundle - composer may then load the newest version of `kriswallsmith/buzz` (0.17.x) which is not backwards compatible to 0.15.x versions.

This is because in the composer.json this dependency is configured `~0.15`, see https://github.com/ctsmedia/contao-phpbb-bridge-bundle/blob/master/composer.json#L21

This then causes the error noted in the issue title.

This can be reproduced by clearing the forum cache in the maintenance section of contao while having `kriswallsmith/buzz`  0.17.x installed.

----

Workaround until this is fixed:

Add the following package conflict to the projects composer.json and update:

```
"conflict": {
      "kriswallsmith/buzz": ">=0.16"
    }
```

This should uninstall newer versions of this package and install install the latest version  of 0.15.x

**Comment by DanielSchwiperich** [comment]
ok we need to fix this. 
this is also happen for users using the composer package. see #42 

According to the changelog the BC break is in 0.17.x https://github.com/kriswallsmith/Buzz/blob/master/CHANGELOG.md#removed-bc-breaks
